### ISSUE TITLE
BUG: Error creating NodePool while deploying on GKE

### ISSUE THREAD

**Issue by HarshCasper** [alan-turing-institute/binderhub-deploy-gke#29]
## Description

Hi 👋 

I am running `./src/deploy.sh` and have configured the GCP Project credentials and the `config.json` already. I am running into this error due to which I was not able to deploy the BinderHub on GKE:

```sh
google_container_node_pool.primary_node_pool: Creating...
╷
│ Warning: Version constraints inside provider configuration blocks are deprecated
│ 
│   on main.tf line 12, in provider "google":
│   12:     version     = "3.46.0"
│ 
│ Terraform 0.13 and earlier allowed provider version constraints inside the provider configuration block, but that is now
│ deprecated and will be removed in a future version of Terraform. To silence this warning, move the provider version constraint
│ into the required_providers block.
╵
╷
│ Error: error creating NodePool: googleapi: Error 400: Auto_repair cannot be false when release_channel REGULAR is set., badRequest
│ 
│   with google_container_node_pool.primary_node_pool,
│   on main.tf line 40, in resource "google_container_node_pool" "primary_node_pool":
│   40: resource "google_container_node_pool" "primary_node_pool" {
│ 
```

I would be highly obliged if this can be fixed to automate the deployment (Thanks for this project!).

**Comment by HarshCasper** [comment]
cc: @sgibson91

**Comment by sgibson91** [comment]
Thanks for the bug report! I'll try to get to it as soon as I can, but I am the only active maintainer of this project just so you're aware :)

**Comment by HarshCasper** [comment]
Hi @sgibson91 

I followed this commit to fix this error: https://github.com/melbourne-cdth/binderhub-deploy-gke/commit/9568b8528ef05878a9075c88d29226e66ed91417

The setup seems to work properly and I'm getting a few errors just around the `gcloud` which I will fix myself.
